# sharpe, calmar, sortino, omega, serenity, smart sharpe, smart sortino
fitness-ratio: 'smart sharpe'
optimal-total: 100

optimizer: 'StochasticHillClimbingOptimizer'
n_iter: 1000

# -1 all cpu
n_jobs: 8

# 'EvolutionStrategyOptimizer'
EvolutionStrategyOptimizer:
  population: 300
  mutation_rate: 0.0333
  crossover_rate: 0.6
  rand_rest_p: 0.05 # swapping_prob


# 'RandomRestartHillClimbingOptimizer'
RandomRestartHillClimbingOptimizer:
  epsilon: 0.3
  distribution: "normal"
  n_neighbours: 4
  rand_rest_p: 0.1 # swapping_prob
  n_iter_restart: 30

# 'RandomRestartHillClimbingOptimizer'
StochasticHillClimbingOptimizer:
  epsilon: 0.3
  distribution: "normal"
  n_neighbours: 4
  rand_rest_p: 0.1 # swapping_prob
  n_iter_restart: 30

strategy_name: 'RaptorMKIV'

starting_balance: 1000
fee: 0.00075
futures_leverage: 1
futures_leverage_mode: cross
settlement_currency: USDT
warm_up_candles: 1000
exchange: Binance
symbol: 'LUNA-USDT'
timeframe: '15m'

timespan-train:
  start_date: '2021-10-01'
  finish_date: '2022-01-01'
timespan-testing:
  start_date: '2021-01-01'
  finish_date: '2022-03-08'

extra_routes:
  0:
    exchange: 'Binance'
    symbol: 'LUNA-USDT'
    timeframe: '15m'
